Added seperate buttons for Start / Stop on Recording and Streaming - v2
bitfocus/companion-module-obs-studio pull request #41
Opened 2020-12-11 07:54 UTC by mattehalen

lets see if this one works better

2020-12-11 07:59 UTC, eric commented
Looks great!

2020-12-12 05:47 UTC, eric approved these changes
This looks great and I could see using this.

2020-12-16 23:25 UTC, mattehalen commented
made some more updates here if someone wanna take a look and approve.

2020-12-17 02:04 UTC, eric requested changes
There are some issues with naming mixing snake case and camel case.

2020-12-17 02:04 UTC, eric commented on index.js
> +		'enable_StudioMode': {
```suggestion
		'enable_studio_mode': {
```

2020-12-17 02:04 UTC, eric commented on index.js
> +		'disable_StudioMode': {
```suggestion
		'disable_studio_mode': {
```

2020-12-17 02:04 UTC, eric commented on index.js
> +		'toggle_StudioMode': {
```suggestion
		'toggle_studio_mode': {
```

2020-12-17 02:04 UTC, eric commented on index.js
> +		'start_ReplayBuffer': {
```suggestion
		'start_replay_buffer': {
```

2020-12-17 02:04 UTC, eric commented on index.js
> +		'stop_ReplayBuffer': {
```suggestion
		'stop_replay_buffer': {
```

2020-12-17 02:04 UTC, eric commented on index.js
> +		'save_ReplayBuffer': {
```suggestion
		'save_replay_buffer': {
```

2020-12-17 02:04 UTC, eric commented on index.js
> +		case 'enable_StudioMode':
```suggestion
		case 'enable_studio_mode':
```

2020-12-17 02:04 UTC, eric commented on index.js
> +		case 'disable_StudioMode':
```suggestion
		case 'disable_studio_mode':
```

2020-12-17 02:04 UTC, eric commented on index.js
> +		case 'toggle_StudioMode':
```suggestion
		case 'toggle_studio_mode':
```

2020-12-17 02:04 UTC, eric commented on index.js
> +		case 'start_ReplayBuffer':
```suggestion
		case 'start_replay_buffer':
```

2020-12-17 02:04 UTC, eric commented on index.js
> +		case 'stop_ReplayBuffer':
```suggestion
		case 'stop_replay_buffer':
```

2020-12-17 02:04 UTC, eric commented on index.js
> +		case 'save_ReplayBuffer':
```suggestion
		case 'save_replay_buffer':
```

2020-12-17 11:07 UTC, mattehalen commented
> There are some issues with naming mixing snake case and camel case.

These should be fixed now

2020-12-19 02:24 UTC, merged